language: node_js
node_js:
  - "0.12"
  - "0.10"
sudo: false
before_install:
  - npm install -g grunt-cli
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
